name: Release

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    tags:
      - 'v*'
    branches: [timeline]
    paths:
      - ".github/workflows/release.yml"
      # - ".changeset/**"
      - "src/**"
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true #  Don't block the release, release notes can be added manually

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      # - name: Publish to npm
      #   run: |
      #     npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      #     npm version patch -m "ci: upgrade to %s"
      #     npm publish --provenance --access public
      #   env:
      #     NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - if: "!contains(github.event.head_commit.message, 'ci: version packages')"
        name: Create Version PR or Publish to NPM
        uses: changesets/action@v1
        with:
          commit: "ci: version packages"
          title: "ci: version packages"
          publish: npm run v:ci:publish-packages
          version: npm run v:ci:version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true